version: '3.8'

services:
  backend:
    build: .
    container_name: pet_ms
    ports:
      - "8000:8000"
    depends_on:
      - mysql_db
    networks:
      - app_network

  mysql_db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: petdev
      MYSQL_USER: petdev
      MYSQL_PASSWORD: petdev
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - app_network
    restart: always
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

networks:
  app_network:
    driver: bridge

volumes:
  mysql_data:
